package:
  name: nodejs
  version: 4.4.0

build:
  number: {{environ.get('BINSTAR_BUILD', 1)}}

source:
  fn: node-v4.4.0-linux-x64.tar.gz [linux64]
  url: https://nodejs.org/dist/v4.4.0/node-v4.4.0-linux-x64.tar.gz [linux64]
  sha256: 114a865effcff2783022ef0fcd30d1e51624d6c28140db0bdc662bcd0f850d8b [linux64]

  fn: node-v4.4.0-darwin-x64.tar.gz [osx]
  url: https://nodejs.org/dist/v4.4.0/node-v4.4.0-darwin-x64.tar.gz [osx]
  sha256: 650c2f1e186a4974304b652321fbb3c4bd22ee7bc7c2c406c6e244dd6a6d38be [osx]

test:
  commands:
    - node --help
    - node --version
    - npm --version

about:
  home: http://nodejs.org/
  license: V8
