package:
  name: nodejs
  version: 0.12.7

build:
  number: {{environ.get('BINSTAR_BUILD', 1)}}

source:
  fn: node-v0.12.7-linux-x64.tar.gz [linux64]
  url: https://nodejs.org/dist/v0.12.7/node-v0.12.7-linux-x64.tar.gz [linux64]
  md5: 182175d82395171f299e3a05a2ce70a1 [linux64]

  fn: node-v0.12.7-darwin-x64.tar.gz [osx]
  url: https://nodejs.org/dist/v0.12.7/node-v0.12.7-darwin-x64.tar.gz [osx]
  md5: ca4897256e00f5b8523cb84e85ad83ea [osx]

test:
  commands:
    - node --help
    - node --version
    - npm --version

about:
  home: http://nodejs.org/
  license: V8
