package:
  name: nodejs
  version: 4.2.2

build:
  number: {{environ.get('BINSTAR_BUILD', 1)}}

source:
  fn: node-v4.2.2-linux-x64.tar.gz [linux64]
  url: https://nodejs.org/dist/v4.2.2/node-v4.2.2-linux-x64.tar.gz [linux64]
  sha256: 5c39fac55c945be3b8ac381a12bdbe3a64a9bdc5376d27e2ce0c72160eff5942 [linux64]

  fn: node-v4.2.2-darwin-x64.tar.gz [osx]
  url: https://nodejs.org/dist/v4.2.2/node-v4.2.2-darwin-x64.tar.gz [osx]
  sha256: 17e60f59cfd40bd0a74f62106dfe2d6cf14aea53490c5e872fa7530138d0dfef [osx]

test:
  commands:
    - node --help
    - node --version
    - npm --version

about:
  home: http://nodejs.org/
  license: V8
