package:
  name: nodejs
  version: 4.2.3

build:
  number: {{environ.get('BINSTAR_BUILD', 1)}}

source:
  fn: node-v4.2.3-linux-x64.tar.gz [linux64]
  url: https://nodejs.org/dist/v4.2.3/node-v4.2.3-linux-x64.tar.gz [linux64]
  sha256: 644d4c0b206ebcb75383fbe42f6025e7253a61992816289359d0f4dcdb6087d7 [linux64]

  fn: node-v4.2.3-darwin-x64.tar.gz [osx]
  url: https://nodejs.org/dist/v4.2.3/node-v4.2.3-darwin-x64.tar.gz [osx]
  sha256: 078b033d98367da2248b443ed74f0b8a5808783d07cf0c24884457fd66b68fc1 [osx]

test:
  commands:
    - node --help
    - node --version
    - npm --version

about:
  home: http://nodejs.org/
  license: V8
