package:
  name: nodejs
  version: 0.12.5

build:
  number: {{environ.get('BINSTAR_BUILD', 1)}}

source:
  fn: node-v0.12.5-linux-x64.tar.gz [linux64]
  url: https://nodejs.org/dist/v0.12.5/node-v0.12.5-linux-x64.tar.gz [linux64]
  md5: d27a934de4763550e0f9fd180428b0be [linux64]

  fn: node-v0.12.5-darwin-x64.tar.gz [osx]
  url: https://nodejs.org/dist/v0.12.5/node-v0.12.5-darwin-x64.tar.gz [osx]
  md5: 0d7ed0f9aab35c791b8064f18b6e2745 [osx]

test:
  commands:
    - node --help
    - node --version
    - npm --version

about:
  home: http://nodejs.org/
  license: V8
